checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableStrictSsl: false

injectEnvironmentFiles:
  - .env.yarn

nodeLinker: node-modules

npmPublishAccess: restricted

npmPublishRegistry: "https://npm.pkg.github.com"

npmScopes:
  khsura:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_GITHUB_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
